### ISSUE TITLE
Some images are stretched on smaller displays

### ISSUE THREAD

**Issue by nexusvoyager** [Dispensa-App/website#1]
So I Opened the web page on my laptop display (1366 x 768) and I noticed that these images looked stretched (see image blow)
![image](https://user-images.githubusercontent.com/79197022/174658853-f4a5f2df-9d78-4efc-940b-abf5e4be3230.png)

I pulled it to my 1080P monitor and it looks fine on full screen, this could be a css thing just double check it :smile: (excuse the low video quality, I had to lower the resolution to fit the video requirements for github)

https://user-images.githubusercontent.com/79197022/174659036-e063a204-2b3d-446d-a3ed-af1bd256369f.mp4

**Comment by nicolapreda** [comment]
I saw that in some formats he makes this joke, probably it is due to some tailwind tag, today I take a look at it.

**Comment by nicolapreda** [comment]
> I saw that in some formats he makes this joke, probably it is due to some tailwind tag, today I take a look at it.

sorry for the slow response, I was on vacation and I missed your notification: /

**Comment by nexusvoyager** [comment]
> I saw that in some formats he makes this joke, probably it is due to some tailwind tag, today I take a look at it.
ah gotcha
> sorry for the slow response, I was on vacation and I missed your notification: /
No problem, I take weeks to respond to my github issues soo :laughing:

**Comment by nexusvoyager** [comment]
Oops I closed it

**Comment by nicolapreda** [comment]
> Oops I closed it

Ok, I worked to fix this error, and I have the problem only for the image into the section "products expiration". Currently I only deleted grids and insert into center the content.In future I will replace that image with another one, because I changed a lot of frontend in my application
